SELECT 
     REGIONID,
     REPLACE(REGIONID,'A', 'REGION')
FROM KOPO_CHANNEL_SEASONALITY_NEW     
;

--KOPO_CUSTOMERDATA의 고객코드는10자리이다
--만약 10자리가 아니면 왼쪽에 0으로 채운다
--이후 고객코드의 뒷 4자리는 암호화를 위해 * 처리를
--해야합니다. hint: 새로운 LPAD, SUBSTR, REPLACE를 활용해서 풀어낼 수 있습니다.


SELECT * FROM KOPO_CUSTOMERDATA;

select
--10자리
LPAD(CUSTOMERCODE, 10, '0')
-- 뒷 4자리
SUBSTR(LPAD(CUSTOMERCODE,10,'0'),-4),
REPLACE(LPAD(CUSTOMERCODE,10,'0')
        ,SUBSTR(LPAD(CUSTOMERCODE,10,'0'),-4)
        ,'****')
from kopo_customerdata
;

--NUMBER_EXAMPLE에
--FIRST/NUMBER를 활용하여 아래와 같은
--결과를 출력하세요

SELECT * FROM NUMBER_EXAMPLE;

SELECT 
        FIRST_NUMBER
        ,SECOND_NUMBER
        ,FIRST_NUMBER/SECOND_NUMBER AS AVG
        ,ROUND(FIRST_NUMBER/SECOND_NUMBER, 2) AS ROUND_EX
        ,CEIL(FIRST_NUMBER/SECOND_NUMBER) AS CEIL_EX
        ,FLOOR(FIRST_NUMBER/SECOND_NUMBER) AS FLOOR_EX
        ,MOD(FIRST_NUMBER/SECOND_NUMBER) AS MOD_EX
        ,POWER(FIRST_NUMBER/SECOND_NUMBER) AS POW_EX
        FROM NUMBER_EXAMPLE
 ;
        
--RMSE_MAE_EXAMPLE2 테이블에서
--ACCURACY =
--1 ? ABS(예측값-실제값) / 예측값 공식을 활용하여
--정확도를 산출하세요 (소수점 2째자리 반올림)

        
SELECT * FROM RMSE_MAE_EXAMPLE2       ;

SELECT 
      YEARWEEK
      --실제값
      ,ACTUAL
      --예측값
      ,FCST
      --정확도
      ,ROUND((1-ABS(FCST-ACTUAL)/FCST),4)*100 AS ACCURACY
      FROM RMSE_MAE_EXAMPLE2
 ;
 
 --날짜 함수
 SELECT
       SYSDATE,
       NEXT_DAY(SYSDATE,2),
       LAST_DAY(SYSDATE)
FROM DUAL
;
SELECT TO_CHAR(SYSDATE-7, 'YYYYWW') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYWW') FROM DUAL;

SELECT TO_CHAR(SYSDATE-30, 'YYYYMMDD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;

SELECT TO_CHAR(SYSDATE-1, 'YYYYMMDD') FROM DUAL;

SELECT TO_CHAR(SYSDATE+7, 'YYYY MM DD') || '일' FROM DUAL;

--일반함수 CASE 사용하기

-- 조건문
SELECT 
    YEARWEEK,
    CASE WHEN QTY<1000 THEN 1000
         WHEN QTY>1000 AND QTY <10000 THEN 10000
         ELSE 30000 END AS QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW
;
