
--union all
SELECT REGIONID, QTY
FROM
(
    SELECT *  FROM KOPO_CHANNEL_RESULT_A01
    UNION 
    SELECT *  FROM KOPO_CHANNEL_RESULT_A02
    )
;
--union    
SELECT REGIONID, QTY FROM KOPO_CHANNEL_RESULT_A01
UNION 
SELECT REGIONID, QTY FROM KOPO_CHANNEL_RESULT_A02;

--EXPRESSION 이용하기(AS 항목 이름 선언 CAST는 타입 변환

select
    'KOPO_D510' AS MEASUREID,
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME
FROM KOPO_PRODUCT_VOLUME;

select
    'KOPO_D510' AS MEASUREID,
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME,
    CAST(YEARWEEK AS NUMBER) * VOLUME AS TEST
FROM KOPO_PRODUCT_VOLUME;

--DISTINCT 중복된 값 제거


SELECT * FROM KOPO_CHANNEL_SEASONALITY;

SELECT DISTINCT REGIONID
         , PRODUCTGROUP
         , PRODUCT
         ,YEARWEEK
         , WEEK
         , QTY
         FROM KOPO_CHANNEL_SEASONALITY;


--상품군(PRODUCTGROUP)에 대한 DISTINCT 구현 후 컬럼이름을 PRODUCT로 변경해보세요
         
SELECT DISTINCT PRODUCTGROUP
        AS PRODUCT
      FROM KOPO_CHANNEL_SEASONALITY;    
      
   
                 
SELECT * FROM ALL_DB_LINKS
DROP DATABASE LINK server111;